<template>
  <div class="app-container">
    <el-form v-show="showSearch" :inline="true" :model="queryParams">
      <el-form-item label="供应商名称"><el-input v-model="queryParams.name" clearable placeholder="请输入名称" @keyup.enter="getList" /></el-form-item>
      <el-form-item label="审批状态"><el-select v-model="queryParams.approvalStatus" clearable placeholder="请选择"><el-option label="草稿" value="DRAFT" /><el-option label="审批中" value="IN_REVIEW" /><el-option label="退回" value="RETURNED" /><el-option label="已准入" value="APPROVED" /></el-select></el-form-item>
      <el-form-item><el-button type="primary" icon="Search" @click="getList">查询</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item>
    </el-form>
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="Plus" @click="openAdd" v-hasPermi="['supply:supplier:add']">新增供应商</el-button></el-col><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" /></el-row>
    <el-table v-loading="loading" :data="list"><el-table-column prop="number" label="单号" min-width="180" /><el-table-column prop="name" label="供应商名称" min-width="180" /><el-table-column prop="taxId" label="税号" min-width="180" /><el-table-column prop="contact" label="联系人" width="100" /><el-table-column prop="approvalStatus" label="状态" width="110"><template #default="s"><el-tag :type="statusType(s.row.approvalStatus)">{{ statusText(s.row.approvalStatus) }}</el-tag></template></el-table-column><el-table-column prop="currentNode" label="当前节点" width="110" /><el-table-column label="操作" width="220"><template #default="s"><el-button link type="primary" @click="openEdit(s.row)" v-if="['DRAFT','RETURNED'].includes(s.row.approvalStatus)" v-hasPermi="['supply:supplier:edit']">编辑</el-button><el-button link type="primary" @click="handleSubmit(s.row)" v-if="['DRAFT','RETURNED'].includes(s.row.approvalStatus)" v-hasPermi="['supply:supplier:edit']">提交</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    <el-dialog v-model="dialogVisible" :title="form.documentId ? '编辑供应商' : '新增供应商'" width="680px"><el-form ref="formRef" :model="form" :rules="rules" label-width="120px"><el-form-item label="供应商名称" prop="name"><el-input v-model="form.name" maxlength="200" /></el-form-item><el-form-item label="统一社会信用代码" prop="taxId"><el-input v-model="form.taxId" maxlength="18" /></el-form-item><el-form-item label="联系人" prop="contact"><el-input v-model="form.contact" /></el-form-item><el-form-item label="联系电话" prop="phone"><el-input v-model="form.phone" /></el-form-item><el-form-item label="地址" prop="address"><el-input v-model="form.address" /></el-form-item><el-form-item label="开户行" prop="bankName"><el-input v-model="form.bankName" /></el-form-item><el-form-item label="账户名称" prop="accountName"><el-input v-model="form.accountName" /></el-form-item><el-form-item label="银行账号" prop="bankAccount"><el-input v-model="form.bankAccount" /></el-form-item><el-form-item label="资质附件"><el-upload :auto-upload="false" :show-file-list="true" :limit="1" accept=".pdf,.png,.jpg,.jpeg" :on-change="queueAttachment" :on-remove="clearAttachment"><el-button>选择资质文件</el-button></el-upload><span class="ml8">{{ pendingFiles.length ? "保存时自动上传 " + pendingFiles.length + " 个" : "请至少选择一个 PDF、PNG 或 JPG 文件" }}</span></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" /></el-form-item></el-form><template #footer><el-button type="primary" @click="save">保存并上传</el-button><el-button @click="dialogVisible = false">取消</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts" name="SupplySupplier">

import { addSupplier, listSuppliers, submitSupplier, updateSupplier, uploadDocumentAttachment } from '@/api/supply'
import type { Supplier } from '@/types/api/supply'
const { proxy } = getCurrentInstance()!
const list = ref<Supplier[]>([]); const loading = ref(false); const total = ref(0); const showSearch = ref(true); const dialogVisible = ref(false)
const queryParams = reactive({ pageNum: 1, pageSize: 20, name: undefined as string | undefined, approvalStatus: undefined as string | undefined }); const form = ref<Supplier>({}); const formRef = ref(); const pendingFiles = ref<File[]>([])
const rules = { name: [{ required: true, message: '供应商名称不能为空', trigger: 'blur' }], taxId: [{ required: true, message: '税号不能为空', trigger: 'blur' }], contact: [{ required: true, message: '联系人不能为空', trigger: 'blur' }], phone: [{ required: true, message: '联系电话不能为空', trigger: 'blur' }], address: [{ required: true, message: '地址不能为空', trigger: 'blur' }], bankName: [{ required: true, message: '开户行不能为空', trigger: 'blur' }], accountName: [{ required: true, message: '账户名称不能为空', trigger: 'blur' }], bankAccount: [{ required: true, message: '银行账号不能为空', trigger: 'blur' }] }
async function getList() { loading.value = true; try { const res = await listSuppliers(queryParams); list.value = res.rows; total.value = res.total } finally { loading.value = false } }
function resetQuery() { queryParams.pageNum = 1; queryParams.name = undefined; queryParams.approvalStatus = undefined; getList() }
function openAdd() { form.value = {}; pendingFiles.value = []; dialogVisible.value = true }
function openEdit(row: Supplier) { form.value = { ...row }; pendingFiles.value = []; dialogVisible.value = true }
async function save() { await formRef.value.validate(); if (form.value.documentId) await updateSupplier(form.value); else { const response = await addSupplier(form.value); form.value.documentId = response.data?.documentId } if (form.value.documentId && pendingFiles.value.length) { await Promise.all(pendingFiles.value.map(file => uploadDocumentAttachment(form.value.documentId!, file, 'QUALIFICATION'))); pendingFiles.value = [] } proxy.$modal.msgSuccess('保存成功'); dialogVisible.value = false; getList() }
function queueAttachment(uploadFile: any) { pendingFiles.value = uploadFile.raw ? [uploadFile.raw as File] : [] }
function clearAttachment() { pendingFiles.value = [] }
function handleSubmit(row: Supplier) { proxy.$modal.confirm(`确认提交供应商“${row.name}”吗？`).then(() => submitSupplier(row.documentId!)).then(() => { proxy.$modal.msgSuccess('已提交审批'); getList() }).catch(() => {}) }
function statusText(value?: string) { return ({ DRAFT: '草稿', IN_REVIEW: '审批中', RETURNED: '退回修改', APPROVED: '已准入', VOID: '已作废' } as Record<string, string>)[value || ''] || value }
function statusType(value?: string) { return value === 'APPROVED' ? 'success' : value === 'IN_REVIEW' ? 'warning' : value === 'RETURNED' ? 'danger' : 'info' }
getList()
</script>
